services:

  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    networks:
      - auth

  keycloak:
    build: .
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - KC_DB_SCHEMA=auth_keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=123456
      - KC_HOSTNAME=localhost
    command: start-dev
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - auth

networks:
  auth:
    name: auth
